- hosts: mhost1
  become: yes
  tasks:
    - name: install Apache package on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: install httpd on Red Hat
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

