---
- hosts: mhost1
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
      tags: maki-tag


    - name: start httpd
      service:
        name: httpd
        state: started
      tags: mo-tag  
      
