---
- hosts: all
  become: yes
  tasks:
  - name: install and start httpd package
    yum:
      name: httpd
      state: present


  - name: start httpd
    service:
      name: httpd
      state: started
