---
- hosts: mhost1
  become: yes
  tasks:
    - name: start and enabl the httpd service
      service:
        name: httpd
        state: latest
        enabled: yes


    - name: start and enable the firewalld
      service:
        name: firewalld
        state: latest
        enabled: yes
        

