---
- hosts: mhost1
  become: yes
  tasks:
    - name: install httpd package
      yum:
        name: httpd
        systemd:
          name: httpd
          state: restarted
          enabled: yes


    - name: start and enabled the firewalld
      systemd:
        name: firewalld
        state: restarted
        enabled: yes
